### ISSUE TITLE
Layout: separation of games in Moves window

### ISSUE THREAD

**Issue by DonZampano** [Watzmann/TGSClient#3]
Layout problem:
Currently the single games are not separated in the Moves window.
Moves are recorded one after other, even if a new game starts.

**Comment by Watzmann** [comment]
hi - yes - known issue - repair until Beta-Release

On Wed, Dec 30, 2015 at 4:04 PM, DonZampano notifications@github.com
wrote:

> Layout problem:
> Currently the single games are not separated in the Moves window
> Moves are recorded one after other, even if a new game starts
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Watzmann/TGSClient/issues/3.

## 

Dr. Andreas Hausmann
ajh.hausmann@gmail.com
+49 176 8325 1592
+49 621 1540 5021
